### PR TITLE
Remove foundries.io from the list of members

### PR DESCRIPTION
**Pull request by gctucker**
As foundries.io is no longer a member of the LF project, update the home page and documentation accordingly.  Also remove the logo file as it's not used anywhere else.

### CODE REVIEW

**Comment by patersonc** [comment]
https://foundation.kernelci.org/ also needs to be updated.

**Comment by gctucker** [comment]
> https://foundation.kernelci.org/ also needs to be updated.

Good point, and that's outside GitHub.  But I can take care of that too.  Maybe let's wait for this to be merged first.

**Comment by gctucker** [comment]
Looking fine on staging.

Home page:
https://static.staging.kernelci.org/#td-block-5

Members page:
https://static.staging.kernelci.org/docs/org/members/

**Comment by glunardi** [comment]
> Home page: https://static.staging.kernelci.org/#td-block-5

Reported-by: guy.lunardi@collabora.com
Tested-by: guy.lunardi@collabora.com



> Members page: https://static.staging.kernelci.org/docs/org/members/

Reported-by: guy.lunardi@collabora.com
Tested-by: guy.lunardi@collabora.com

**Comment by glunardi** [comment]
Thank you very much @gctucker 

Please go ahead and make the changes on wordpress as well if you could.

Thanks in advance.

**Pull request merged**
