### PR TITLE
Remove legacy KernelCI system documentation

### PR DESCRIPTION
**Pull request by padovan**
We are about to shutdown the legacy system, so this documetation is not really useful anymore.

### CODE REVIEW

**Comment by nuclearcat** [comment]
I think seems better to delete legacy entries, as they are confusing people.

**Comment by patersonc** [comment]
@padovan do you think you could rebase this PR? Perhaps it's time we merged it?

**Comment by padovan** [comment]
@nuclearcat @pawiecz can you take this over please?

**Comment by nuclearcat** [comment]
As requested https://github.com/kernelci/kernelci-project/pull/491

**Pull request closed without merging**
