### PR TITLE
Record 2024-06-21 TSC votes

### PR DESCRIPTION
**Pull request by spbnick**
Record the votes concluded on 2024-06-21.

### CODE REVIEW

**Comment by padovan** [comment]
Looks good to me.

**Review by gctucker — APPROVED** [review]
Note: The maintainers page needs to be updated accordingly with the list of GitHub owners.

**Comment by patersonc** [comment]
> Note: The maintainers page needs to be updated accordingly with the list of GitHub owners.

@spbnick do you want to do this in this PR? Or a new one?

**Comment by spbnick** [comment]
I think the maintainers page is mostly about people, really, and `thelinuxfoundation` shouldn't go there, as this is a bot account, as I understand it, and doesn't really "maintain" anything.

**Comment by spbnick** [comment]
As such, let's merge this, and if there's disagreement, we can add a change on top.

**Comment by spbnick** [comment]
Could somebody merge this, please? I don't have the permissions.

**Pull request merged**
