### PR TITLE
docs: update style colors to match branding

### PR DESCRIPTION
**Pull request by padovan**
Make it KernelCI colors :)

No rush to merge this. We can complete the DNS change first.

### CODE REVIEW

**Comment by patersonc** [comment]
It would be good to see this on staging before merging

**Comment by nuclearcat** [comment]
According to https://github.com/kernelci/kernelci-project/actions/runs/9493897767/job/26163335914 it should be deployed on staging

**Review by patersonc — APPROVED** [review]
Seems to look okay to me.

**Pull request merged**
