### PR TITLE
Record 2024-07-11 TSC votes

### PR DESCRIPTION
**Pull request by spbnick**
Record the votes concluded on 2024-07-11.

### CODE REVIEW

**Comment by nuclearcat** [comment]
All ok on staging: https://static.staging.kernelci.org/org/tsc/votes/#2024-07-11

**Review by nuclearcat — APPROVED** [review]
LGTM

**Comment by spbnick** [comment]
Thanks, Denys :heart:

**Comment by aliceinwire** [comment]
LGTM

**Pull request merged**
