### PR TITLE
votes.md: Add voting records for motion at #2024-09-05

### PR DESCRIPTION
**Pull request by nuclearcat**
MOTION: Add Paweł Wieczorek to the sysadmin working group

### CODE REVIEW

**Comment by patersonc** [comment]
Hi @nuclearcat 

Thanks for the PR.

Looking at the changelist it looks like there are some submodule changes in your commt. Was this intentional?

**Comment by nuclearcat** [comment]
I am going to test it after we merge @padovan changes. I need to check why this is happening.

**Comment by patersonc** [comment]
> I am going to test it after we merge @padovan changes. I need to check why this is happening.

FYI I've merged the other PRs now.

**Comment by spbnick** [comment]
LGTM!

**Review by aliceinwire — APPROVED** [review]

**Comment by nuclearcat** [comment]
/staging
I removed submodule changes.

**Pull request merged**
