### PR TITLE
kernelci.org: clarify the duties of TSC members

### PR DESCRIPTION
**Pull request by gctucker**
Add a Duties section on the TSC page to clarify what TSC members are meant to be doing or responsible for.  Update the wording of the Members section accordingly.  This should be based on current proceedings and is merely about documenting them without introducing anything new.

### CODE REVIEW

**Review by patersonc — APPROVED** [review]
LTGM, thanks

**Comment by gctucker** [comment]
Thanks, I'll wait until it's deployed on the staging website to check it looks as expected.

**Comment by gctucker** [comment]
I've also updated the date on the page.

**Comment by gctucker** [comment]
Verified on staging: https://static.staging.kernelci.org/docs/org/tsc/

**Pull request merged**
