### PR TITLE
switch to a docs-only Hugo pages

### PR DESCRIPTION
**Pull request by padovan**
Our main website is going to be the Foundation website, so we are making this one only about the documentation.
All the doc pages were moved to the root dir as we expect a DNS switch to `docs.kernelci.org` for this website.

**NOTES** 

* This PR contains commits from other MRs.
* We should synchonize the merge and deploy with the switch of the DNS entries.

### CODE REVIEW

**Review by patersonc — COMMENTED** [review]
The code looks okay.
Can you remind me what the link is for the staging site to see it in action?

**Comment by pawiecz** [comment]
@patersonc Should be https://static.staging.kernelci.org but I don't see the changes introduced in this PR deployed there :thinking:

**Comment by nuclearcat** [comment]
/staging
It will be generated now (after few min) to https://static.staging.kernelci.org

**Comment by nuclearcat** [comment]
Staging must be fine now, please check

**Comment by patersonc** [comment]
We may want to consider updating https://static.staging.kernelci.org/org/maintainers/#project

**Comment by gctucker** [comment]
> We may want to consider updating https://static.staging.kernelci.org/org/maintainers/#project

I was about to send an email to the TSC with some proposed motions for that, to replace me with another maintainer ;)

**Comment by patersonc** [comment]
> I was about to send an email to the TSC with some proposed motions for that, to replace me with another maintainer ;)

I was referring more to updating it to say the static site is now just the documentation site rather than the whole kernelci.org - rather than demoting you @gctucker :D

**Comment by padovan** [comment]
> We may want to consider updating https://static.staging.kernelci.org/org/maintainers/#project

I added another commit to update the description.

**Comment by padovan** [comment]
I also added a commit to use the new URL with the upcoming DNS switch.

**Comment by patersonc** [comment]
Do you plan to remove the blogs directory in a follow-up PR?

**Comment by padovan** [comment]
> Do you plan to remove the blogs directory in a follow-up PR?

Yeah. I don't think there is a harm of leaving them there for the time being. The Blog link points to the Wordpress website already.

**Comment by patersonc** [comment]
> > Do you plan to remove the blogs directory in a follow-up PR?
> 
> Yeah. I don't think there is a harm of leaving them there for the time being. The Blog link points to the Wordpress website already.

Okay.  
Google search may still find the blog pages here, but as the content is the same I guess it doesn't really matter.

I'd like to see the latest version on staging before merging, and perhaps we should wait for the DNS changes to be ready.

**Pull request merged**
