### PR TITLE
Port content from foundation site to static docs site

### PR DESCRIPTION
**Pull request by patersonc**
First PR towards resolving #43

### CODE REVIEW

**Comment by patersonc** [comment]
Previews available here:
* https://static.staging.kernelci.org/docs/org/
* https://static.staging.kernelci.org/docs/org/members/

Formatting on the members page needs to be improved

**Comment by patersonc** [comment]
The members page _should_ look okay now. We'll see for sure when it gets picked up by staging.

**Review by mgalka — APPROVED** [review]
Layout and content look good to me.

**Review by gctucker — COMMENTED** [review]
LGTM.  Maybe mention in the commit messages that the content was taken from foundation.kernelci.org?

**Comment by patersonc** [comment]
> LGTM. Maybe mention in the commit messages that the content was taken from foundation.kernelci.org?

Done

**Pull request merged**
