### PR TITLE
kernelci.org: update admin section summary

### PR DESCRIPTION
**Pull request by gctucker**
Update the landing page of the admin section accordingly to the fact that we're now focusing on the new API rather than the legacy system.

### CODE REVIEW

**Review by nuclearcat — APPROVED** [review]
LGTM, looks fine on staging: https://static.staging.kernelci.org/docs/admin/

**Comment by nuclearcat** [comment]
Unfortunately i can't merge it

**Comment by gctucker** [comment]
PS This was a preparation for adding another page, I'll send another PR after this one.

**Comment by gctucker** [comment]
> Unfortunately i can't merge it

That's fine, it's the last repo where I'm still the actual maintainer ;)

**Pull request merged**
