### PR TITLE
.github/ISSUE_TEMPLATE: update `api-early-access` template

### PR DESCRIPTION
**Pull request by JenySadadia**
Update `kci` commands in the template for creating GH issue for user account request.

### CODE REVIEW

**Review by pawiecz — APPROVED** [review]
LGTM

**Comment by JenySadadia** [comment]
> LGTM
> 
> nit: path is `.github/ISSUE_TEMPLATE` but that's not really a reason to amend this PR

Opps, another type. Let me fix the commit message.

**Comment by JenySadadia** [comment]
@nuclearcat Could you please merge this? I don't have merge rights.

**Review by nuclearcat — APPROVED** [review]
LGTM

**Pull request merged**
