### PR TITLE
kernelci.org: Add KCIDB docs

### PR DESCRIPTION
**Pull request by spbnick**
Embed the reorganized KCIDB documentation.

Concerns kernelci/kcidb#213

### CODE REVIEW

**Comment by spbnick** [comment]
Note that the commit in this PR refers to an unmerged KCIDB commit from kernelci/kcidb#238.

**Comment by gctucker** [comment]
Deployed OK on staging: https://static.staging.kernelci.org/docs/kcidb/

**Comment by gctucker** [comment]
FYI I had to make this change in the script that updated the website on staging: https://github.com/kernelci/kernelci-deploy/commit/8e049b88e9029d7ddad544707753f0886be9bb56

This is because the `kcidb` project doesn't have an automatically generated `staging.kernelci.org` branch.  It's not an issue per se, but if you want PRs that change the documentation to be automatically deployed on staging without having to constantly update the submodule revision we could enable that.  The submodule revision would still need to be updated after the PRs have been merged in `kcidb`.

**Comment by spbnick** [comment]
> FYI I had to make this change in the script that updated the website on staging: [kernelci/kernelci-deploy@8e049b8](https://github.com/kernelci/kernelci-deploy/commit/8e049b88e9029d7ddad544707753f0886be9bb56)
> 
> This is because the `kcidb` project doesn't have an automatically generated `staging.kernelci.org` branch. It's not an issue per se, but if you want PRs that change the documentation to be automatically deployed on staging without having to constantly update the submodule revision we could enable that. The submodule revision would still need to be updated after the PRs have been merged in `kcidb`.

Ah, I remember you mentioning that. I guess it flew over my head back then :grin: Yes, that would be good to have that generated automatically, thank you!

**Comment by gctucker** [comment]
OK I've added that now.  For example, if someone makes a PR to draw a diagram with Mermaid it should appear automatically on the staging website.

**Comment by spbnick** [comment]
Alright, this now points to a merged commit. Would you consider merging this, @gctucker? Thank you.

**Review by gctucker — APPROVED** [review]
Looks OK on staging

**Pull request merged**
