### PR TITLE
kernelci.org: add API admin page

### PR DESCRIPTION
**Pull request by gctucker**
Add an API page to the sysadmin section about how to create an admin token and how to add users.

### CODE REVIEW

**Review by nuclearcat — APPROVED** [review]
LGTM, visible and properly formatted on staging: https://static.staging.kernelci.org/docs/admin/api/

**Comment by gctucker** [comment]
Thanks, I guess it would be good to try and go through the instructions while addressing #251.

**Comment by gctucker** [comment]
@nuclearcat Hello, do you have any feedback on this PR now that you've followed the steps to create a new user account?

**Comment by nuclearcat** [comment]
Works very well for me and sufficient for now. Maybe later we will do self-registration with approval, but that's future thing.

**Pull request merged**
