### PR TITLE
docs: add the new Web Dashboard to the menu

### PR DESCRIPTION
**Pull request by padovan**
We should also add a note on the dashboard many parts of it are still under development, but we are already able to add value to some users (and get feedback from them). So let's show it.

### CODE REVIEW

**Comment by patersonc** [comment]
Do you think we're ready for this change then?

Did we want to weaken the link a bit and call it something like `Dashboard (WIP)` or `New Dashboard`?

**Comment by helen-fornazier** [comment]
> Do you think we're ready for this change then?
> 
> Did we want to weaken the link a bit and call it something like `Dashboard (WIP)` or `New Dashboard`?

`New Dashboard` is more in the sense that this is a new thing, but not that it is work in process, so WIP reflects more in this regard.

Could we show a small "About" notice on bottom left?

Screenshot from 2024-09-05 14-21-46


Something like this:

```
NOTE: this dashboard is still in alpha version,
if you experience any issue, please send
us feedback.
Version: 0.0.1
Licence: ...
GitHub: ...
```

Besides that, we could have an "About" section as a tab, we could explain this dashboard is still under development, point to links to the source code and some usage information. It would be interesting to have a pointer to "Want to see your tree here? Request it in through link". Or, if easier, this "About" tab button could redirect to the GitHub project with a nice README

**Comment by padovan** [comment]
I made it `Dashboard (WIP)` then

@helen-fornazier yes, let's ask ProFUSION to add such a note to the Web Dashboard

/staging

**Comment by padovan** [comment]
Screenshot from 2024-09-06 13-28-52

Change is looking good now. I rebased it on top of latest main, so it is ready to merge now.

**Review by patersonc — APPROVED** [review]
Thanks

**Pull request merged**
