### PR TITLE
Add organization section with project charter documents

### PR DESCRIPTION
**Pull request by gctucker**
Rename the Team section to Organization and add the project charter documents.

### CODE REVIEW

**Comment by gctucker** [comment]
Deployed on staging: https://static.staging.kernelci.org/docs/org/

**Comment by spbnick** [comment]
LGTM in general, but PDF links on the deployed page give me 404.
Also, do you want to handle redirection from the old locations?

**Comment by gctucker** [comment]
> LGTM in general, but PDF links on the deployed page give me 404.

Fixed, well spotted.  The relative URLs were missing a leading `/`.  Thanks!

> Also, do you want to handle redirection from the old locations?

That may be done separately.  The funding charter was not stored anywhere before, and the technical one used to be here:
https://storage.kernelci.org/files/LF/kernelCI_Project_Technical_Charter_20181107.pdf

If there are any links on the frontend or anywhere then they should probably be updated to point to the new page.  But I think that's outside the scope of this PR, unless you meant something else?

**Comment by spbnick** [comment]
> If there are any links on the frontend or anywhere then they should probably be updated to point to the new page. But I think that's outside the scope of this PR, unless you meant something else?

I meant these:
https://kernelci.org/docs/team/board/ -> https://kernelci.org/docs/org/board/
https://kernelci.org/docs/team/tsc/ -> https://kernelci.org/docs/org/tsc/

**Comment by spbnick** [comment]
I mean we might need to add a redirect to the renamed pages in case anyone was linking to them before.

Also this one, of course:
https://kernelci.org/docs/team/ -> https://kernelci.org/docs/org/

**Comment by gctucker** [comment]
Ah yes, good point.  I'll follow this approach:
https://gohugo.io/content-management/urls/#example-aliases

Also some internal links to the `team` section should be updated.  Fixing this now.

**Comment by gctucker** [comment]
New version deployed on staging, same URL.

The old URLs from the team section now redirect to the org section:
* https://static.staging.kernelci.org/docs/team/tsc/
* https://static.staging.kernelci.org/docs/team/board/

**Comment by gctucker** [comment]
Ah except the base URL for redirects is a bit broken apparently on staging, let's fix that now...

**Comment by gctucker** [comment]
@spbnick OK should be all fixed now, please take another look.

**Comment by spbnick** [comment]
Hmm, the old https://static.staging.kernelci.org/docs/team/ still works and shows the site having "Teams", but no "Organization". Is this some caching/cleanup issue?

**Comment by gctucker** [comment]
Alright fixed that too now with an alias for the whole section (team -> org).

And yes the old files for the team section were still there, the Hugo site rebuild didn't delete them.  That's why the Team section was still available.  It's all cleaned up now, but I'll investigate why it didn't do it automatically.

**Comment by spbnick** [comment]
Perfect now :relieved: Thanks :grin:! ACK!

**Review by spbnick — APPROVED** [review]

**Pull request merged**
