### PR TITLE
kci-dev: Add kci-dev to KernelCI documentation

### PR DESCRIPTION
**Pull request by aliceinwire**

### CODE REVIEW

**Comment by aliceinwire** [comment]
@patersonc can you authorize it in staging but don't merge it yet? currently trying to test this PR

**Comment by aliceinwire** [comment]
we converted the kci-dev documentation to gohugo for been added to kernelci-project
https://github.com/kernelci/kci-dev/pull/48

**Comment by aliceinwire** [comment]
> /staging

staging looks stuck at 5 months ago

**Comment by aliceinwire** [comment]
ready to be merged

**Comment by nuclearcat** [comment]
I will prepare PR and merge it today

**Comment by nuclearcat** [comment]
Works now: https://static.staging.kernelci.org/kci-dev/

**Pull request merged**
