### PR TITLE
upd(website): Update Slack to Discord

### PR DESCRIPTION
**Pull request by nuclearcat**
According to TSC voting we are migrating to Discord. All links and content need to be updated accordingly.

### CODE REVIEW

**Comment by nuclearcat** [comment]
/staging
@padovan

**Comment by patersonc** [comment]
Should we add some details about the Matrix <> Discord bridge that @aliceinwire set up?

**Comment by patersonc** [comment]
Slack is also mentioned in two github templates:
```
.github/ISSUE_TEMPLATE/new-tsc-member.md:15:- [ ] New member invited to any relevant [Slack](https://kernelci.slack.com) private channels (if applicable)
.github/ISSUE_TEMPLATE/api-staging-access.md:14:[Staging deployment](https://github.com/kernelci/kernelci-api/tree/main/kube/aks) can already run a pipeline with KUnit, kselftest, kernel builds and boot tests. So please give it a go and create issues on GitHub and ask  questions on the [mailing list](mailto:kernelci@lists.linux.dev), IRC `#kernelci` on libera.chat or [Slack](https://kernelci.slack.com) with whatever you may find.
```

**Review by patersonc — APPROVED** [review]
LGTM

**Pull request merged**
