### PR TITLE
kernelci.org: Update KernelCI bigger picture

### PR DESCRIPTION
**Pull request by aliceinwire**
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>

### CODE REVIEW

**Comment by aliceinwire** [comment]
@gctucker can you update the image of the KernelCI documentation? 
I think you are the original author.

**Comment by gctucker** [comment]
What do you want to change?

**Comment by aliceinwire** [comment]
> What do you want to change?

Just updating it to the last LPC 2020 presentation slide image

**Comment by gctucker** [comment]
Oh I think that one might be from Nikolai's talk.  I didn't have any talk at LPC 2021, I was busy enough managing the micro-conf :)

@spbnick Could you please provide the "bigger picture" diagram from your talk as PNG so we can update it on the website, or directly send a PR with it using Git LFS?

**Pull request closed without merging**
