### PR TITLE
.github/ISSUE_TEMPLATE: staging account request template

### PR DESCRIPTION
**Pull request by JenySadadia**
Update template to provide details for requesting staging user account. Remove the details for early-access request as the early access phase has ended.

### CODE REVIEW

**Comment by patersonc** [comment]
LGTM, any change requests from anyone else?

**Comment by nuclearcat** [comment]
No, i guess lets merge it!

**Comment by JenySadadia** [comment]
Opps, the line breaks don't look nice on issue preview.

**Comment by nuclearcat** [comment]
Then follow up PR can fix it :)

**Pull request merged**
